### ISSUE TITLE
Publish new installation guide

### ISSUE THREAD

**Issue by ricardoalcocer** [ricardoalcocer/appc_book_code#2]
With changes in the Appcelerator Website, the download, installation and configuration process has changed.  As soon as this information becomes clear, I'll be publishing a new PDF that will replace Appendix B.

**Comment by captainZ3ro** [comment]
Hi Ricardo, I'm wondering if I'm suffering some installation issues. I just signed up for Appcelerator Studio and the only app's I've gotten to run are the default empty app. Here's what I get when I run the MP3 code: 

[ERROR] Application Installer abnormal process termination. Process exit value was 1
[INFO] :   Aligning zip file: /Users/caseysteffen/Library/android-sdk-macosx/build-tools/22.0.1/zipalign "-v" "4" "/Volumes/Source/BiologicDesigns/Projects/AppDev/appc_book_code-master/ch2/mp3player/build/android/bin/singlewindow.apk" "/Volumes/Source/BiologicDesigns/Projects/AppDev/appc_book_code-master/ch2/mp3player/build/android/bin/singlewindow.apkz"
[ERROR] :  Failed to zipalign apk:
[ERROR] :  Output file '/Volumes/Source/BiologicDesigns/Projects/AppDev/appc_book_code-master/ch2/mp3player/build/android/bin/singlewindow.apkz' exists
titanium exited with exit code 1

What do you suggest? Do I need to wait for them to provide installation diagnosis?

thanks, Casey

**Comment by ricardoalcocer** [comment]
Responded via email.  This error is fixed by cleaning your project, either by doing `Project > Clean` in Studio, or doing `ti clean` (or `appc ti clean`) in the terminal/command window.
