### ISSUE TITLE
Changing Default.png and Appicon.png

### ISSUE THREAD

**Issue by captainZ3ro** [ricardoalcocer/appc_book_code#6]
Hey Ricardo, I for the life of me can not figure out how to change the default icons for the conference app. What am I missing? I believe I have my image files named and sized correctly. Any ideas?

Casey

**Comment by ricardoalcocer** [comment]
Hi, do you mean the tab icons?  They're here: https://github.com/ricardoalcocer/appc_book_code/blob/master/ch4/app/styles/index.tss
